### ISSUE TITLE
Swap glide for godep

### ISSUE THREAD

**Issue by katzien** [golang-bristol/beer-server#14]
It's looking like [godep](https://github.com/tools/godep) is going to become the official dependency manager for Go, so why not switch to it.

**Comment by theGeekPirate** [comment]
Included in PR https://github.com/golang-bristol/beer-server/pull/15

**Comment by gmichokostas** [comment]
Are you sure [godep](https://github.com/tools/godep) is going to be the official dependency manager for Go and not [dep](https://github.com/golang/dep) ? I thought it was the second one, at least from what I read [here](https://github.com/golang/dep/wiki/Roadmap).
In any case I am more that happy to tackle this.

**Comment by theGeekPirate** [comment]
I actually used dep in my PR, which is the correct version (Godep hasn't been updated since Feb.). I assumed they were the same =b

**Comment by katzien** [comment]
Haha, yup, good point, I meant dep! @theGeekPirate read my mind correctly haha
